wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 1000000000
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715465129
    t:
      1:
      - 1
      - 35
      - 55
      2:
      - 1
      - 35
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.14
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
